display_set_gui_size(1280, 720);
randomize();
gpu_set_texfilter(true);
vv_ui_init();
available_leaders = make_enemy_leader_registry();
available_scenarios = make_scenario_registry();
selected_leader_index = 0;
selected_scenario_index = 0;
enemy_leader = available_leaders[selected_leader_index];
enemy_scenario = available_scenarios[selected_scenario_index];
available_heroes = make_hero_definitions();
selected_hero_ids = make_default_hero_selection(available_heroes);
enemy_event_selection = make_default_enemy_event_selection(enemy_leader, enemy_scenario);
log_lines = [];
setup_active = true;
phase = "setup";
refresh_setup_validation();
vv_assets_init();
vv_assets_load_initial();
